apiVersion: v1
kind: Service
metadata:
  name: grpc-server-headless
  namespace: grpc-server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
