apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-custom-hpa
  namespace: grpc-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric: 
        name: grpc_requests_per_second
      target:
        type: AverageValue
        averageValue: 300m
