apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: grpc-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: jolly3/grpc-client:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRPC_SERVER_DOMAIN
              value: envoy.envoy.svc.cluster.local
            - name: GRPC_SERVER_PORT
              value: "8443"
      imagePullSecrets:
        - name: regcred
