{
 "title": "gRPC Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(grpc_requests_total)" }
   ]
  },
  {
   "title": "Request Latency p95",
   "type": "timeseries",
   "description": "The histogram_quantile function uses the data from sum(rate(grpc_request_latency_seconds_bucket[1m])) to estimate the latency value at the 95th percentile. In other words, it calculates the value below which 95% of the requests fall.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Rate of gRPC requests processed per second over the last minute",
   "type": "timeseries",
   "description": "gives you the total rate of gRPC requests processed per second over the last minute, aggregated across all instances or services that report this metric. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(grpc_requests_total[1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rate of gRPC Requests in the Last 5 Minutes per Pod",
   "type": "timeseries",
   "description": "The result of this query will be the total number of grpc_requests_total that have occurred within the past 5 minutes. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(grpc_requests_total[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}